"""Slack webhook delivery using Block Kit formatting."""

import requests
from datetime import datetime


def send_slack_briefing(webhook_url: str, papers: list[dict], stats: dict | None = None) -> bool:
    """Send formatted briefing to Slack via incoming webhook.

    Args:
        webhook_url: Slack incoming webhook URL
        papers: List of dicts with keys: paper (Paper obj), score (float), summary (str)
        stats: Optional dict with source stats (e.g. {"total_fetched": 87, "after_dedup": 68})

    Returns True if successful.
    """
    try:
        # Build header and context
        today = datetime.now().strftime("%B %d, %Y")
        context_text = f"{len(papers)} papers · {today}"
        if stats:
            total = stats.get("total_fetched")
            dedup = stats.get("after_dedup")
            if total and dedup:
                context_text += f" · {total} fetched → {dedup} after dedup"

        blocks = [
            {
                "type": "header",
                "text": {"type": "plain_text", "text": "📚 Daily Paper Briefing"}
            },
            {
                "type": "context",
                "elements": [{"type": "mrkdwn", "text": context_text}]
            },
            {"type": "divider"}
        ]

        # Add paper blocks (max 10)
        for i, item in enumerate(papers[:10], 1):
            paper = item["paper"]
            score = item["score"]
            summary = item["summary"]

            # Choose emoji based on score
            emoji = "🔥" if score >= 0.8 else "⭐" if score >= 0.6 else "📄"

            # Main section with title and summary
            title_link = f"*<{paper.url}|{paper.title}>*"
            section_text = f"{emoji} {title_link}\n{summary}"

            blocks.append({
                "type": "section",
                "text": {"type": "mrkdwn", "text": section_text}
            })

            # Context line: authors + journal + score
            authors = paper.authors[:3] if paper.authors else []
            author_str = ", ".join(authors)
            if len(paper.authors) > 3:
                author_str += " et al."

            context_parts = [author_str] if author_str else []
            if paper.journal:
                context_parts.append(paper.journal)
            context_parts.append(f"{int(score * 100)}%")

            if paper.arxiv_pdf_url:
                context_parts.append(f"| <{paper.arxiv_pdf_url}|arXiv PDF>")

            blocks.append({
                "type": "context",
                "elements": [{"type": "mrkdwn", "text": " · ".join(context_parts)}]
            })
            blocks.append({"type": "divider"})

        # Footer
        blocks.append({
            "type": "context",
            "elements": [{"type": "mrkdwn", "text": "Generated by AtomOra 🔬"}]
        })

        # Send to Slack
        payload = {"blocks": blocks}
        response = requests.post(webhook_url, json=payload, timeout=10)
        response.raise_for_status()

        print(f"✓ Sent briefing to Slack ({len(papers)} papers)")
        return True

    except Exception as e:
        print(f"✗ Failed to send Slack briefing: {e}")
        return False
